name: 'Hello World'
description: 'Greet someone'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  filter-log:
    description: "Filtered unit test log"
    value: ${{ steps.run_unit_tests.outputs.filter-log }}
runs:
  using: "composite"
  steps:
    - name : rand num
      run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - name : step 1
      id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - name : step 2
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name : step 3
      id: run_unit_tests
      shell: bash
      run: |
        MY_STRING=$(cat << EOF
        first line
        second line
        third line
        EOF
        )
        echo "::set-output name=filter-log::$MY_STRING"
   #     echo "MY_STRING<<EOF" >> $GITHUB_ENV
   #     echo "$MY_STRING" >> $GITHUB_ENV
   #     echo "EOF" >> $GITHUB_ENV
      id: string-ggen
    
